In [54]:
from mpmath import mp, matrix
import numpy as np


class GaussEliminationSolver:
    def __init__(self, A, B, sf=5):
        self.sf = sf
        mp.dps = self.sf
        self.n= A.rows
        self.A = mp.matrix(A)
        self.B = mp.matrix(B)

    def scaling(self):
        scaling_factors = mp.matrix([0] * self.n)
        for i in range(self.n):
            scaling_factors[i, 0] = max([abs(self.A[i, j]) for j in range(i + 1)])
        return scaling_factors

    def gaussian_elimination(self):
        augmented_matrix = matrix(
            [[self.A[i, j] for j in range(self.A.cols)] + [self.B[i, 0]] for i in range(self.A.rows)])
        n = augmented_matrix.rows

        print("Initial Augmented Matrix:")
        print(augmented_matrix)

        scaling_factors = self.scaling()

        for i in range(n):
            max_index = max(range(i, n), key=lambda x: abs(
                augmented_matrix[x, i] / scaling_factors[x]))

            if i != max_index:
                print(f"\nSwapping rows {i + 1} and {max_index + 1}:")
                augmented_matrix[i, :], augmented_matrix[max_index,
                                                         :] = augmented_matrix[max_index, :], augmented_matrix[i, :]
                print(augmented_matrix)

            for j in range(i + 1, n):
                factor = augmented_matrix[j, i] / augmented_matrix[i, i]
                print(
                    f"\nRow {j + 1} = Row {j + 1} - ({factor}) * Row {i + 1}:")
                augmented_matrix[j, :] -= factor * augmented_matrix[i, :]
                print(augmented_matrix)

        return augmented_matrix

    def back_substitution(self, augmented_matrix):
        n = len(augmented_matrix)
        solution = matrix([mp.mpf(0)] * n)

        for i in range(n - 1, -1, -1):
            # Fetch the constant from the augmented matrix
            solution[i] = mp.mpf(augmented_matrix[i, n])

            for j in range(i + 1, n):
                solution[i] -= mp.mpf(augmented_matrix[i, j]) * solution[j]

            solution[i] /= mp.mpf(augmented_matrix[i, i])

        return solution


# Example usage:
A = matrix([[-8, 1, -2],
            [-3, -1, 7],
            [2, -6, 1]])

B = matrix([[106.8],
            [177.2],
            [279.2]])

solver = GaussEliminationSolver(A, B)
augmented_matrix = solver.gaussian_elimination()
solution = solver.back_substitution(augmented_matrix)

print("\nSolution:")
print(solution)

Initial Augmented Matrix:
[-8.0   1.0  -2.0  106.8]
[-3.0  -1.0   7.0  177.2]
[ 2.0  -6.0   1.0  279.2]

Row 2 = Row 2 - (0.375) * Row 1:
[-8.0     1.0  -2.0   106.8]
[ 0.0  -1.375  7.75  137.15]
[ 2.0    -6.0   1.0   279.2]

Row 3 = Row 3 - (-0.25) * Row 1:
[-8.0     1.0  -2.0   106.8]
[ 0.0  -1.375  7.75  137.15]
[ 0.0   -5.75   0.5   305.9]

Swapping rows 2 and 3:
[-8.0     1.0  -2.0   106.8]
[ 0.0   -5.75   0.5   305.9]
[ 0.0  -1.375  7.75  137.15]

Row 3 = Row 3 - (0.23913) * Row 2:
[-8.0    1.0    -2.0  106.8]
[ 0.0  -5.75     0.5  305.9]
[ 0.0    0.0  7.6304   64.0]

Solution:
[-22.006]
[-52.471]
[ 8.3875]


In [57]:
from mpmath import mp, matrix
from Solver import Solver

class GaussEliminationSolver(Solver):

    def solve(self):
        augmented_matrix = self.gaussian_elimination()
        solution = self.back_substitution(augmented_matrix)
        return solution

    def gaussian_elimination(self):
        A,B = self.A,self.B
        augmented_matrix = matrix([[A[i, j] for j in range(A.cols)] + [B[i, 0]] for i in range(A.rows)])
        n = augmented_matrix.rows

        self.steps.append("Initial Augmented Matrix:")
        self.steps.append(augmented_matrix)

        for i in range(n):
            max_index = max(range(i, n), key=lambda x: abs(augmented_matrix[x, i]))

            if i != max_index:
                self.steps.append(f"\nSwapping rows {i + 1} and {max_index + 1}:")
                augmented_matrix[i, :], augmented_matrix[max_index, :] = augmented_matrix[max_index, :], augmented_matrix[i, :]
                self.steps.append(augmented_matrix)


            for j in range(i + 1, n):
                factor = augmented_matrix[j, i] / augmented_matrix[i, i]
                self.steps.append(f"\nRow {j + 1} = Row {j + 1} - ({factor}) * Row {i + 1}:")
                augmented_matrix[j, :] -= factor * augmented_matrix[i, :]
                self.steps.append(augmented_matrix)

        return augmented_matrix

    def back_substitution(self, augmented_matrix):
        n = len(augmented_matrix)
        solution = matrix([mp.mpf(0)] * n)  

        for i in range(n - 1, -1, -1):
            solution[i] = mp.mpf(augmented_matrix[i, n])  # Fetch the constant from the augmented matrix

            for j in range(i + 1, n):
                solution[i] -= mp.mpf(augmented_matrix[i, j]) * solution[j]

            solution[i] /= mp.mpf(augmented_matrix[i, i])

        return solution


    

# Example 
A = matrix([[-8, 1, -2],
            [-3, -1, 7],
            [2, -6, 1]])

B = matrix([[106.8],
            [177.2],
            [279.2]])

a = GaussEliminationSolver(A,B)
solution = a.back_substitution(a.gaussian_elimination())
print(solution)

[-22.006]
[-52.471]
[ 8.3875]
